=== RemiBardon/PMN4/TP1/Chronotachygraphe/chronotachygraphe.dtd
<!ELEMENT chronotachygraphe (vehicule, carte*) >
<!ELEMENT vehicule (anomalie*) >
<!ELEMENT anomalie (#PCDATA) >
<!ELEMENT carte (conducteur | entreprise) >
<!ELEMENT conducteur (activite*) >
<!ELEMENT activite EMPTY >
<!ELEMENT entreprise (session*) >
<!ELEMENT session EMPTY >

<!ATTLIST chronotachygraphe
    dureeFonctionnement CDATA       #REQUIRED
    dateRevision        CDATA       #REQUIRED
    etatVerrou          (oui|non)   "non"
>

<!ATTLIST vehicule
    immatriculation ID              "non"
    statut          (solo|equipage) "solo"
>

<!ATTLIST anomalie
    date    CDATA                   #REQUIRED
    panne   (moteur|cabine|plateau) #REQUIRED
>

<!ATTLIST carte
    couleur     (jaune|blanche)         #REQUIRED
    heure       CDATA                   #REQUIRED
    date        CDATA                   #REQUIRED
    action      (insertion|extraction)  #REQUIRED
>

<!ATTLIST conducteur
    nom             NMTOKENS    #REQUIRED
    prenom          NMTOKENS    #REQUIRED
    numPermis       ID          #REQUIRED
    tempsService    CDATA       #REQUIRED
>

<!ATTLIST activite
    type    (conduite|repas|travail|disponibilite)  "conduite"
    vitesse CDATA                                   #REQUIRED
    date    CDATA                                   #REQUIRED
    duree   CDATA                                   #REQUIRED
>

<!ATTLIST entreprise
    nom     NMTOKENS    #REQUIRED
    adresse CDATA       #REQUIRED
    statut  CDATA       #REQUIRED
>

<!ATTLIST session
    immatriculation     IDREF       #REQUIRED
    destination         NMTOKENS    #REQUIRED
    estVide             (oui|non)   #IMPLIED
    distance            CDATA       #REQUIRED
    numPermis           IDREF       #REQUIRED
>

=== RemiBardon/PMN4/TP1/Chronotachygraphe/chronotachygraphe1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE chronotachygraphe SYSTEM "chronotachygraphe.dtd">
<chronotachygraphe dureeFonctionnement="1440" dateRevision="20200129">
    <vehicule>
        <anomalie date="20200129" panne="moteur">Une panne moteur</anomalie>
    </vehicule>
    <carte couleur="blanche" heure="1200" date="20200129" action="insertion">
        <entreprise nom="Dupond" adresse="Marine" statut="Boss"></entreprise>
    </carte>
    <carte couleur="blanche" heure="1201" date="20200129" action="extraction">
        <entreprise nom="Dupond" adresse="Marine" statut="Boss"></entreprise>
    </carte>
    <carte couleur="jaune" heure="1204" date="20200129" action="insertion">
        <conducteur nom="Dupont" prenom="Jean" numPermis="p1234" tempsService="0"></conducteur>
    </carte>
    <carte couleur="jaune" heure="1249" date="20200129" action="extraction">
        <conducteur nom="Dupont" prenom="Jean" numPermis="p1234" tempsService="45"></conducteur>
    </carte>
</chronotachygraphe>
